########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  ######## Stellar ########
  # Stellar 最近更新日志（10条记录）
  
  ######## Volantis ########
  # Volantis 最近更新日志（10条记录）

  ######## xaoxuu ########
  - https://api.github.com/users/zsxcoder
  # - https://api.github.com/users/xaoxuu/followers
  # - https://api.github.com/users/xaoxuu/following
  # 我的仓库列表
  # - https://api.github.com/users/xaoxuu/repos?per_page=100
  # 我的博客热门文章
  # - https://api.github.com/repos/xaoxuu/blog-comments/issues?sort=comments
  # 我近期动态
  - https://api.github.com/repos/zsxcoder/weibo/issues?per_page=5
  - https://api.github.com/repos/zsxcoder/weibo/issues?per_page=20
